# ===============================
# SERVER
# ===============================
server.port=8080
server.servlet.session.timeout=30m

# ===============================
# DATASOURCE (MySQL)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hce_prueba2?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${MYSQL_ROOT_PASSWORD:}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JACKSON
# ===============================
spring.jackson.time-zone=America/Guayaquil

# ===============================
# LOGGING (SECURITY)
# ===============================
logging.level.org.springframework.security=DEBUG
