# ===============================
# SERVER
# ===============================
server.port=8080
server.servlet.session.timeout=30m
server.forward-headers-strategy=framework
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

# ===============================
# DATASOURCE (MySQL)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hce_prueba2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${MYSQL_ROOT_PASSWORD:root}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
ALLOWED_ORIGINS=http://localhost,http://localhost:4200,http://localhost:5173
HCE_DEFAULT_USER_PASSWORD=cambia_esta_clave_inicial

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JACKSON
# ===============================
spring.jackson.time-zone=America/Guayaquil

# ===============================
# LOGGING (SECURITY)
# ===============================
logging.level.org.springframework.security=DEBUG
